name: RapidRAW - Enhanced CI Build

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
            args: '--bundles nsis'
            target: ''
            asset-prefix: '01'
          - platform: 'windows-11-arm'
            args: '--bundles nsis'
            target: 'aarch64-pc-windows-msvc'
            asset-prefix: '01'
          - platform: 'macos-14'
            target: aarch64-apple-darwin
            asset-prefix: '02'
          - platform: 'macos-15-intel'
            target: x86_64-apple-darwin
            asset-prefix: '02'
          - platform: 'ubuntu-22.04'
            target: ''
            asset-prefix: '03'
          - platform: 'ubuntu-22.04-arm'
            target: ''
            asset-prefix: '03'
          - platform: 'ubuntu-24.04'
            target: ''
            asset-prefix: '03'
          - platform: 'ubuntu-24.04-arm'
            target: ''
            asset-prefix: '03'
          - platform: 'ubuntu-latest'
            mobile: 'android'
            target: 'aarch64-linux-android'
            args: '--target aarch64'
            asset-prefix: '04'
    uses: ./.github/workflows/build.yml
    with:
      platform: ${{ matrix.platform }}
      target: ${{ matrix.target }}
      build-args: ${{ matrix.args }}
      asset-prefix: ${{ matrix.asset-prefix }}
      mobile: ${{ matrix.mobile }}
    secrets: inherit
    permissions:
      contents: write
