name: RapidRAW - Enhanced PR Build

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows x86-64
            platform: windows-latest
            target: x86_64-pc-windows-msvc
            args: --bundles nsis
          - name: macOS ARM64
            platform: macos-14
            target: aarch64-apple-darwin
            args: --bundles dmg
          - name: Ubuntu x86-64
            platform: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
            args: --bundles appimage
          - name: Ubuntu ARM64
            platform: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
            args: --bundles appimage
    uses: ./.github/workflows/build.yml
    with:
      platform: ${{ matrix.platform }}
      target: ${{ matrix.target }}
      build-args: ${{ matrix.args }}
      upload-artifacts: true
    secrets: inherit
    permissions:
      contents: read
